# Днём — нормальный цвет
profile {
    time = 7:00
    identity = true          # 6500K, без изменений
}

# Вечером — тёплый
profile {
    time = 20:00
    temperature = 5000       # можно 3500–5000, чем ниже — тем теплее/оранжевее
    gamma = 0.9              # опционально, чуть снижает яркость
}
